//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSend
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTransfers
    {
        public int TransferId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> EncryptionLevel { get; set; }
        public string TransferredData { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] FileData { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
