//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeSend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.FileTransfers = new HashSet<FileTransfers>();
            this.FileTransfers1 = new HashSet<FileTransfers>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string UDID { get; set; }
        public string DeviceToken { get; set; }
    
        public virtual ICollection<FileTransfers> FileTransfers { get; set; }
        public virtual ICollection<FileTransfers> FileTransfers1 { get; set; }
    }
}
